### ISSUE TITLE
esp-idf-rc522 build error 

### ISSUE THREAD

**Issue by abdellah2288** [abobija/esp-idf-rc522#14]
## Description
esp-idf-rc522.h throws a build error when added as a component
`In file included from /home/abdellah/esp-idf/components/esp-idf-rc522/rc522.c:7:
/home/abdellah/esp-idf/components/esp-idf-rc522/rc522.h:8:10: fatal error: driver/spi_master.h: No such file or directory
    8 | #include <driver/spi_master.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.`
## Solution 
add driver to REQUIRES in CMakeLists.txt
[CMakeLists.txt](https://github.com/abobija/esp-idf-rc522/files/10528183/CMakeLists.txt)

**Comment by abobija** [comment]
Fixed in #15
