### ISSUE TITLE
Crash when rc522 is not connected with multiple devices on same SPI bus

### ISSUE THREAD

**Issue by usmanrazasaif** [abobija/esp-idf-rc522#21]
I have two devices on the SPI bus and rc522 is initialized later with .spi.bus_is_initialized = true. However, when rc522 is not connected, the driver throws an error and esp32 crashes.

Is it possible that it does not crash if rc522 is not connected? Thanks.

The error log is:

E (7397) spi_master: spi_master_deinit_driver(272): not all CSses freed
I (7407) gpio: GPIO[23]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (7417) gpio: GPIO[19]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (7427) gpio: GPIO[18]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0

assert failed: spi_bus_deinit_lock spi_bus_lock.c:599 (atomic_load(&lock->dev[i]) == (intptr_t)NULL)

Backtrace: 0x40082005:0x3ffcd710 0x4008b665:0x3ffcd730 0x400918e1:0x3ffcd750 0x401174c9:0x3ffcd870 0x40116bdd:0x3ffcd890 0x4010fad1:0x3ffcd8b0 0x401100f4:0x3ffcd8d0 0x4011026d:0x3ffcd8f0 0x400d9995:0x3ffcd920 0x400d99db:0x3ffcd970 0x4008e635:0x3ffcda00
0x40082005: panic_abort at E:/Software/Espressif/frameworks/esp-idf-v4.4.5/components/esp_system/panic.c:408

**Comment by abobija** [comment]
Thanks! It's going to be fix as a part of PR #20
