### ISSUE TITLE
Select quantity of UID bytes.

### ISSUE THREAD

**Issue by ASebastianRodriguez** [abobija/esp-idf-rc522#41]
Dear Mr. Bobija,

My name is Sebastián and currently I'm using you library in a home project. The purpose of my message is to ask to you about the change of the quantity of UID bytes, I tried to change the number of bytes within the rc522_anticoll() (line 462 of rc522.c file) function without success.

Please, can you indicate to me the correct way to do it.

Thanks so much for your help.

Best regards,

Sebastián.

**Comment by ASebastianRodriguez** [comment]
Thanks so much Bobija!

**Comment by abobija** [comment]
No problem, thank you for your feedback @ASebastianRodriguez :)
