### ISSUE TITLE
Why is device accessed using SPI_DEVICE_HALFDUPLEX?

### ISSUE THREAD

**Issue by adrien-n** [abobija/esp-idf-rc522#5]
Hi,

First of all, thanks for your work on the library.

I'm trying to use an rc522 on the same bus as an sd card reader through sdspi. I therefore need a single bus configuration that works for both devices. Unfortunately, in practice, sdspi requires setting up the bus to use DMA as far as I can tell (or buffers will be very very small) and devices that use SPI_DEVICE_HALFDUPLEX are not compatible with that (it's slightly more complicated than that actually[1]).

I've tried to remove that flag but then my tags don't get recognized anymore. Initialization (including tests) succeeds. I've tried to understand why it was used but I've got absolutely no idea and I found no reference whatsoever.

Can you shine a light on this matter? Is there a specific reason/timing/reference for this?

Thanks!

[1] https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#spi-known-issues

**Comment by wieserh** [comment]
Well I just adjusted the code to always use full duplex. For my use case there i no downside. There are not many modifications required. I did encounter some issues with heap corruption though, currently trying to find out whether I introduced them and how to fix these.

**Comment by dahmadjid** [comment]
I have rn the same issue. im using a tft screen and sdcard together with the rfid. DMA is necessary for everything to work. @wieserh how easy was it to change everything to full duplex ? do you have a modified branch or any idea on what i should change on my side ? thanks in advance
