### ISSUE TITLE
提示SHA256校验失败 反复重启

### ISSUE THREAD

**Issue by cnlnlhb** [abobija/esp-idf-rc522#6]
您好，我运行了例程，芯片使用的是ESP32-C3，报错SHA256校验失败，反复重启
错误日志：

![image](https://user-images.githubusercontent.com/44800826/148537688-54a423b4-f115-4da7-ad15-8d3cdd67e973.png)

**Comment by cnlnlhb** [comment]
您好，为啥关闭了？

**Comment by abobija** [comment]
@cnlnlhb do you speak english?

**Comment by cnlnlhb** [comment]
@abobija 
Hello, sorry for using Chinese to ask the question earlier. I ran the routine, the chip uses ESP32-C3, and it reported an error that the SHA256 verification failed, and restarted repeatedly. The development environment and hardware do not have this problem when compiling other code.
The error log is as posted before.
Looking forward to your reply, thank you.

**Comment by abobija** [comment]
Did you set target to C3 with the next command `idf.py set-target esp32c3` ?

If that does not resolve your problem it might be some sort of power issues, check this link:
https://www.esp32.com/viewtopic.php?f=13&t=22302
